### ISSUE TITLE
How to get wallpapers to TV?

### ISSUE THREAD

**Issue by milindpatel63** [adelatour11/androidtvbackground#1]
How do you get the generated wallpapers to your tv in a automated way?
Do you somehow run the script on your tv?
I'm running Projectivy Launcher.

**Comment by Avigrace** [comment]
I run the script on a windows PC

On my Nvidia shield I have enabled remote SMB access then I have a second batch file which does an xcopy, both run through Task Scheduler

**Comment by milindpatel63** [comment]
Hi, i managed to find a better way i think.
Here's my forked repo: https://github.com/milindpatel63/androidtvbackground

I'm running the plex.py (on my personal plex server) and TMDBlogo.py using github actions, and then upload_wallpaper.py to upload the generated images to my subreddit https://www.reddit.com/r/DianaHomeLab
I'm also keeping track of uploaded images using filenames in uploaded_wallpapers.txt

The github action runs daily.

I then use the subreddit as my wallpaper source in projectivy launcher.

Created all this with the help of ChatGPT 4o

**Comment by soderlund91** [comment]
Good you got it working, I did it in a similar way using subreddit.

This is my solution to it: 
Create a subreddit that you could upload images to. I made a python script (with ChatGPT) that uploads, approve and remove old images. 

You also need to create a Reddit App from where you get the client _id and client_secret. 
https://www.reddit.com/prefs/apps 



```
import praw
import os
import time

# Reddit API credentials
REDDIT_CLIENT_ID = 'MY_CLIENT_ID'
REDDIT_CLIENT_SECRET = 'MY_CLIENT_SECRET'
REDDIT_USER_AGENT = 'MY_USERNAME' #Could be anything, it don't really matter
REDDIT_USERNAME = 'MY_USERNAME'
REDDIT_PASSWORD = 'MY_PASSWORD'

# Subreddit and directory settings
SUBREDDIT_NAME = 'MY_SUB'
IMAGE_DIRECTORY = '/path/to/my/images/'

# Initialize Reddit instance
reddit = praw.Reddit(
    client_id=REDDIT_CLIENT_ID,
    client_secret=REDDIT_CLIENT_SECRET,
    user_agent=REDDIT_USER_AGENT,
    username=REDDIT_USERNAME,
    password=REDDIT_PASSWORD
)

def upload_images():
    # Get the subreddit
    subreddit = reddit.subreddit(SUBREDDIT_NAME)

    # List existing posts to find which to delete
    existing_posts = list(subreddit.new(limit=100))  # Adjust limit as needed

    # Upload new images
    for image_file in os.listdir(IMAGE_DIRECTORY):
        if image_file.endswith(('.png', '.jpg', '.jpeg', '.gif')):
            image_path = os.path.join(IMAGE_DIRECTORY, image_file)
            post = subreddit.submit_image(title=image_file, image_path=image_path)
            print(f"Uploaded: {image_file}")

            # Auto-approve the post if you're a moderator
            if post.mod:
                post.mod.approve()
                print(f"Approved post: {post.title}")

    # Delete old posts
    for post in existing_posts:
        post.delete()
        print(f"Deleted post: {post.title}")

if __name__ == '__main__':
    upload_images()

```
